# Generated by Django 5.2.7 on 2025-10-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('contenu', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sport_media')),
            ],
        ),
    ]
