# Generated by Django 5.2.7 on 2025-10-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prix', models.FloatField(default=0.0)),
                ('qte', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
