# Generated by Django 5.2.7 on 2025-10-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='qte',
        ),
    ]
