# Generated by Django 5.2.7 on 2025-10-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0004_commande_lignecommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
