# Generated by Django 5.2.7 on 2025-10-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0005_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
