# Generated by Django 5.2.7 on 2025-10-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0006_lignecommande_prix_unitaire_alter_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
