# Generated by Django 5.2.7 on 2025-10-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0007_commande_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='qr_code',
        ),
    ]
